name: ui_background_task
description: A Flutter iOS plugin to begin and end a UI Background task. It helps finishing long tasks up to 30s after the app is pushed to background.
version: 0.2.0
homepage: https://github.com/Neelansh-ns/ui_background_task
repository: https://github.com/Neelansh-ns/ui_background_task

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  stop_watch_timer: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: UiBackgroundTaskPlugin
